name: Nancy.Expressions-test

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'Nancy/Nancy.Expressions/*'
      - 'Nancy/Nancy.Expressions.Tests/*'
  pull_request:
    branches:
      - master
    paths:
      - 'Nancy/Nancy.Expressions/*'
      - 'Nancy/Nancy.Expressions.Tests/*'

jobs:
  Nancy-Expressions-test:
    runs-on: ubuntu-latest
    
    env:
      BUILD_CONFIG: "Release"
      SOLUTION: "Nancy/Nancy.sln"
      NANCY_EXPRESSIONS: "Nancy/Nancy.Expressions/Nancy.Expressions.csproj"
      NANCY_EXPRESSIONS_TESTS: "Nancy/Nancy.Expressions.Tests/Nancy.Expressions.Tests.csproj"

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Build Nancy.Expressions
        run: dotnet build $NANCY_EXPRESSIONS --configuration $BUILD_CONFIG

      - name: Build Nancy.Expressions.Tests
        run: dotnet build $NANCY_EXPRESSIONS_TESTS --configuration $BUILD_CONFIG

      - name: Test Nancy.Expressions
        run: dotnet test $NANCY_EXPRESSIONS_TESTS /p:Configuration=$BUILD_CONFIG
