name: Nancy.Expressions.Interactive.Local-test

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "Nancy/Nancy.Expressions/*"
      - "Nancy/Nancy.Expressions.Interactive/*"
  pull_request:
    branches:
      - master
    paths:
      - "Nancy/Nancy.Expressions/*"
      - "Nancy/Nancy.Expressions.Interactive/*"

jobs:
  Nancy-Expressions-Interactive-Local-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-sdk-version: [ '8.0.x' ]
        
    env:
      BUILD_CONFIG: "Release"
      SOLUTION: "Nancy/Nancy.sln"
      NANCY_EXPRESSIONS: "Nancy/Nancy.Expressions/Nancy.Expressions.csproj"
      NANCY_EXPRESSIONS_INTERACTIVE: "Nancy/Nancy.Expressions.Interactive/Nancy.Expressions.Interactive.Local.csproj"

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup dotnet ${{ matrix.dotnet-sdk-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-sdk-version }}

      - name: Build Nancy.Expressions
        run: dotnet build $NANCY_EXPRESSIONS --configuration $BUILD_CONFIG

      - name: Build Nancy.Expressions.Interactive.Local
        run: dotnet build $NANCY_EXPRESSIONS_INTERACTIVE --configuration $BUILD_CONFIG

      # No actual tests available
