name: Nancy-test

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'Nancy/Nancy/*'
      - 'Nancy/Nancy.Tests/*'
  pull_request:
    branches:
      - master
    paths:
      - 'Nancy/Nancy/*'
      - 'Nancy/Nancy.Tests/*'

jobs:
  Nancy-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-sdk-version: [ '8.0.x', '9.0.x' ]
        nancy-release: [ "", ".LongRational" ]
    
    env:
      BUILD_CONFIG: "Release"
      SOLUTION: "Nancy/Nancy.sln"
      NANCY: "Nancy/Nancy/Nancy${{ matrix.nancy-release }}.csproj"
      NANCY_TESTS: "Nancy/Nancy.Tests/Nancy.Tests${{ matrix.nancy-release }}.csproj"

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup dotnet ${{ matrix.dotnet-sdk-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-sdk-version }}

      - name: Build Nancy${{ matrix.nancy-release }}
        run: dotnet build $NANCY --configuration $BUILD_CONFIG --framework ${{ matrix.dotnet-sdk-version }}

      - name: Build Nancy.Tests${{ matrix.nancy-release }}
        run: dotnet build $NANCY_TESTS --configuration $BUILD_CONFIG --framework ${{ matrix.dotnet-sdk-version }}

      - name: Test Nancy${{ matrix.nancy-release }}
        run: dotnet test $NANCY_TESTS /p:Configuration=$BUILD_CONFIG --framework ${{ matrix.dotnet-sdk-version }}
